/**
 * Builds the daily digest markdown page that Layer 1 writes to the brain
 * and Layer 2 (the cloud /schedule routine) reads back.
 *
 * Filing convention:
 *   inbox/<work-email-slug>/<YYYY-MM-DD>.md
 *
 * The page is the queue between collector + enricher. Layer 2 reads
 * unprocessed digests, walks each entry, and updates entity timelines.
 * On completion, Layer 2 sets `processed: true` in frontmatter so we
 * don't re-process.
 *
 * Three sections per digest:
 *   ## Signatures pending — DocuSign etc. that need user action
 *   ## Triage — real human emails (the bulk of what Layer 2 acts on)
 *   ## Noise — stripped automated mail (kept for audit, not enriched)
 */

import type { CollectedEmail } from './types.ts';

export function digestSlug(workEmail: string, date: string): string {
  const emailSlug = workEmail.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return `inbox/${emailSlug}/${date}`;
}

function escape(s: string): string {
  // Avoid breaking markdown by stripping pipe/bracket-y chars inside table cells / titles.
  return (s ?? '').replace(/[\r\n]+/g, ' ').trim();
}

function formatTime(iso: string): string {
  // "2026-05-08T14:32:00.000Z" → "14:32 UTC"
  const m = /T(\d{2}):(\d{2})/.exec(iso);
  return m ? `${m[1]}:${m[2]}Z` : iso.slice(0, 16);
}

function formatEntry(e: CollectedEmail): string {
  const direction = e.isOutbound ? '→' : '←';
  const time = formatTime(e.date);
  const who = e.fromName ? `${e.fromName} <${e.fromEmail}>` : e.fromEmail;
  const recipients = e.recipients.length > 3
    ? `${e.recipients.slice(0, 3).join(', ')} (+${e.recipients.length - 3} more)`
    : e.recipients.join(', ');
  const lines: string[] = [];
  lines.push(`- **${time}** ${direction} ${escape(who)}`);
  lines.push(`  - **Subject:** ${escape(e.subject) || '(no subject)'}`);
  lines.push(`  - **${e.isOutbound ? 'To' : 'From → to'}:** ${escape(recipients)}`);
  if (e.snippet) lines.push(`  - **Snippet:** ${escape(e.snippet).slice(0, 250)}`);
  lines.push(`  - **Link:** [Open in Gmail](${e.gmailLink})`);
  lines.push(`  - **Source:** \`gmail/${e.messageId}\``);
  return lines.join('\n');
}

export interface DigestPage {
  slug: string;
  content: string;
  counts: { signatures: number; triage: number; noise: number };
}

export function buildDigest(workEmail: string, date: string, emails: CollectedEmail[]): DigestPage {
  const slug = digestSlug(workEmail, date);
  const signatures: CollectedEmail[] = [];
  const triage: CollectedEmail[] = [];
  const noise: CollectedEmail[] = [];

  for (const e of emails) {
    if (e.isNoise) noise.push(e);
    else if (e.isSignature) signatures.push(e);
    else triage.push(e);
  }

  // Chronological within each section.
  const byDate = (a: CollectedEmail, b: CollectedEmail) => a.date.localeCompare(b.date);
  signatures.sort(byDate);
  triage.sort(byDate);
  noise.sort(byDate);

  const fm = [
    '---',
    `title: Inbox digest — ${workEmail} — ${date}`,
    `slug: ${slug}`,
    'type: inbox-digest',
    'created_via: email-sync',
    `work_email: ${workEmail}`,
    `digest_date: ${date}`,
    `total_emails: ${emails.length}`,
    `signatures: ${signatures.length}`,
    `triage: ${triage.length}`,
    `noise: ${noise.length}`,
    'processed: false',
    `updated: ${new Date().toISOString()}`,
    '---',
  ].join('\n');

  const body: string[] = [];
  body.push(`# Inbox digest — ${workEmail} — ${date}`);
  body.push('');
  body.push(`Auto-generated by email-sync. ${triage.length} triage, ${signatures.length} signatures, ${noise.length} noise.`);
  body.push('');
  body.push('Layer 2 (`/dent-process-inbox`) reads the **Triage** section to update entity timelines. Signatures are surfaced for human action. Noise is kept for audit only.');
  body.push('');

  body.push('## Signatures');
  if (signatures.length === 0) {
    body.push('');
    body.push('_None._');
  } else {
    body.push('');
    for (const e of signatures) body.push(formatEntry(e));
  }
  body.push('');

  body.push('## Triage');
  if (triage.length === 0) {
    body.push('');
    body.push('_None._');
  } else {
    body.push('');
    for (const e of triage) body.push(formatEntry(e));
  }
  body.push('');

  body.push('## Noise');
  if (noise.length === 0) {
    body.push('');
    body.push('_None._');
  } else {
    body.push('');
    for (const e of noise) body.push(formatEntry(e));
  }
  body.push('');

  return {
    slug,
    content: `${fm}\n\n${body.join('\n')}`,
    counts: { signatures: signatures.length, triage: triage.length, noise: noise.length },
  };
}
