#!/usr/bin/env bun
/**
 * Plugin marketplace bundle ↔ VERSION drift check.
 *
 * Reads the canonical `VERSION` from repo root and verifies that every
 * auto-derived plugin-bundle artifact carries the same version. If any
 * artifact drifts (e.g. /ship bumped VERSION but `bun run build:plugin`
 * was never run), exits 1 with instructions to regenerate.
 *
 * Why this exists: dent-brain's release pipeline has a quiet failure mode.
 * The Cowork plugin marketplace bundle is regenerated by `bun run build:plugin`,
 * not by the version bump itself. If /ship bumps VERSION + commits without
 * running build:plugin, the server moves but Claude Desktop's plugin UI is
 * pinned at the previous version forever — teammates running /dent-update
 * see "you're current" even though they're not. This bit us between v0.38
 * and v0.39 (server at 0.39, marketplace bundle stuck at 0.38).
 *
 * CLAUDE.md documents the requirement in prose; this script enforces it.
 *
 * Usage:
 *   bun run check:plugin-version           # exits 0 if in sync, 1 on drift
 *   bun run check:plugin-version --quiet   # silent unless drift
 *
 * Wired into `verify`, so /ship's pre-push gate and CI's pre-test gate both
 * catch the drift before it can land.
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');
const QUIET = process.argv.includes('--quiet');

function log(msg: string) {
  if (!QUIET) console.error(msg);
}

interface Check {
  label: string;
  path: string;
  extract: (raw: string) => string | undefined;
}

const CHECKS: Check[] = [
  {
    label: '.claude-plugin/marketplace.json plugins[0].version',
    path: '.claude-plugin/marketplace.json',
    extract: (raw) => JSON.parse(raw)?.plugins?.[0]?.version,
  },
  {
    label: 'plugin/marketplace/.claude-plugin/plugin.json version',
    path: 'plugin/marketplace/.claude-plugin/plugin.json',
    extract: (raw) => JSON.parse(raw)?.version,
  },
  {
    label: 'plugin/marketplace/manifest.lock.json plugin_version',
    path: 'plugin/marketplace/manifest.lock.json',
    extract: (raw) => JSON.parse(raw)?.plugin_version,
  },
  {
    label: 'plugin/marketplace/VERSION',
    path: 'plugin/marketplace/VERSION',
    extract: (raw) => raw.trim(),
  },
];

const versionPath = join(ROOT, 'VERSION');
if (!existsSync(versionPath)) {
  console.error(`[check:plugin-version] FAIL: ${versionPath} missing`);
  process.exit(1);
}
const expected = readFileSync(versionPath, 'utf-8').trim();

const drift: { label: string; path: string; got: string | undefined }[] = [];

for (const c of CHECKS) {
  const abs = join(ROOT, c.path);
  if (!existsSync(abs)) {
    drift.push({ label: c.label, path: c.path, got: '<file missing>' });
    continue;
  }
  let got: string | undefined;
  try {
    got = c.extract(readFileSync(abs, 'utf-8'));
  } catch (err) {
    drift.push({ label: c.label, path: c.path, got: `<parse error: ${(err as Error).message}>` });
    continue;
  }
  if (got !== expected) {
    drift.push({ label: c.label, path: c.path, got });
  }
}

if (drift.length === 0) {
  log(`[check:plugin-version] OK — marketplace bundle in sync at v${expected}`);
  process.exit(0);
}

console.error(`[check:plugin-version] FAIL: plugin bundle drifts from VERSION (${expected})`);
for (const d of drift) {
  console.error(`  - ${d.label}`);
  console.error(`      file: ${d.path}`);
  console.error(`      got:  ${d.got}`);
  console.error(`      want: ${expected}`);
}
console.error('');
console.error('Fix: bun run build:plugin && git add .claude-plugin plugin/marketplace && git commit');
console.error('Why this matters: if the marketplace bundle lags the server, Claude Desktop\'s');
console.error('plugin UI shows the previous version forever — teammates running /dent-update');
console.error('see "you\'re current" even when they are not.');
process.exit(1);
